### ISSUE TITLE
[vike-solid-query] No QueryClient set, use QueryClientProvider to set one

### ISSUE THREAD

**Issue by rtritto** [vikejs/vike-solid#123]
Created home page from [examples/solid-query](https://github.com/vikejs/vike-solid/tree/main/examples/solid-query).

## Reproduction
1. `git clone https://github.com/rtritto/template-vike-elysia-solid-daisyui.git`
2. `cd template-vike-elysia-solid-daisyui`
3. `git test-solid-query`
4. `yarn`
5. `yarn dev`
6. Navigate to `http://localhost:3000`

## Output
```console
  VITE v5.4.5  ready in 1052 ms
  ➜  Local:   http://localhost:3000/
  ➜  Network: use --host to expose
  ➜  press h + enter to show help
8:11:36 PM [vike][request(1)] HTTP request: /

🌼   daisyUI 4.12.10
├─ ✔︎ 1 theme added             https://daisyui.com/docs/themes
╰─ ❤︎ Support daisyUI project:  https://opencollective.com/daisyui

8:11:37 PM [vike][request(1)] Following error was thrown by the onRenderHtml() hook defined at vike-solid/__internal/integration/onRenderHtml
15 |   if (queryClient) {
16 |     return queryClient;
17 |   }
18 |   const client = useContext(QueryClientContext);
19 |   if (!client) {
20 |     throw new Error("No QueryClient set, use QueryClientProvider to set one");
              ^
error: No QueryClient set, use QueryClientProvider to set one
      at useQueryClient (C:\template-vike-elysia-solid-daisyui\node_modules\@tanstack\solid-query\build\dev.js:20:10)
      at createMemo (C:\template-vike-elysia-solid-daisyui\node_modules\solid-js\dist\server.js:97:10)
      at createBaseQuery (C:\template-vike-elysia-solid-daisyui\node_modules\@tanstack\solid-query\build\dev.js:194:11)
      at Movies (unknown:25:50)
      at createComponent (C:\template-vike-elysia-solid-daisyui\node_modules\solid-js\dist\server.js:359:10)
      at Page (unknown:17:322)
      at createComponent (C:\template-vike-elysia-solid-daisyui\node_modules\solid-js\dist\server.js:359:10)
      at createComponent (C:\template-vike-elysia-solid-daisyui\node_modules\solid-js\dist\server.js:359:10)
      at renderWrappers (C:\template-vike-elysia-solid-daisyui\node_modules\vike-solid\dist\integration\onRenderHtml.js:72:4)
      at children (unknown:32:19)
      at Content (unknown:20:173)
      at createComponent (C:\template-vike-elysia-solid-daisyui\node_modules\solid-js\dist\server.js:359:10)
      at Layout (unknown:30:74)
      at createComponent (C:\template-vike-elysia-solid-daisyui\node_modules\solid-js\dist\server.js:359:10)
      at createComponent (C:\template-vike-elysia-solid-daisyui\node_modules\solid-js\dist\server.js:359:10)
      at children (C:\template-vike-elysia-solid-daisyui\node_modules\vike-solid\dist\hooks\usePageContext.js:12:7)

8:11:37 PM [vike][request(1)] HTTP response / 500
```

## Notes
- Bun is used
- Similar #124

**Comment by phonzammi** [comment]
@rtritto, Thanks for opening this issue.

I can reproduce the issue, and it appears to happen only in development, not in the build. I need to investigate further. Feel free to create a PR to help address this issue.
