### ISSUE TITLE
[vike-solid-query] Qualified path resolution failed: we looked for the following paths, but none could be accessed

### ISSUE THREAD

**Issue by rtritto** [vikejs/vike-solid#124]
Created home page from [examples/solid-query](https://github.com/vikejs/vike-solid/tree/main/examples/solid-query).

## Reproduction
1. `git clone https://github.com/rtritto/template-vike-solid-daisyui.git`
2. `cd template-vike-solid-daisyui`
3. `git test-solid-query`
4. `yarn`
5. `yarn dev`
6. Navigate to `http://localhost:3000`

## Output
```console
  VITE v5.4.5  ready in 2117 ms
  ➜  Local:   http://localhost:3000/
  ➜  Network: use --host to expose
  ➜  press h + enter to show help
20:35:21 [vike][request(1)] HTTP request: /

🌼   daisyUI 4.12.10
├─ ✔︎ 1 theme added             https://daisyui.com/docs/themes
╰─ ❤︎ Support daisyUI project:  https://opencollective.com/daisyui

20:35:22 [vike][request(1)][Error] Transpilation error:
Error: Qualified path resolution failed: we looked for the following paths, but none could be accessed.

Source path: C:\template-vike-solid-daisyui\.yarn\__virtual__\vike-solid-query-virtual-5e8ba09589\3\Users\<USER>\AppData\Local\Yarn\Berry\cache\vike-solid-query-npm-0.0.1-37c4e8e89f-10c0.zip\node_modules\vike-solid-query\dist\src\QueryBoundary
Not found: C:\template-vike-solid-daisyui\.yarn\__virtual__\vike-solid-query-virtual-5e8ba09589\3\Users\<USER>\AppData\Local\Yarn\Berry\cache\vike-solid-query-npm-0.0.1-37c4e8e89f-10c0.zip\node_modules\vike-solid-query\dist\src\QueryBoundary

    at makeError (C:\template-vike-solid-daisyui\.pnp.cjs:12259:34)
    at resolveUnqualified (C:\template-vike-solid-daisyui\.pnp.cjs:13991:13)
    at resolveRequest (C:\template-vike-solid-daisyui\.pnp.cjs:14031:14)
    at Object.resolveRequest (C:\template-vike-solid-daisyui\.pnp.cjs:14087:26)
    at resolve$1 (file:///C:/template-vike-solid-daisyui/.pnp.loader.mjs:2043:21)
    at nextResolve (node:internal/modules/esm/hooks:750:28)
    at Hooks.resolve (node:internal/modules/esm/hooks:238:30)
    at handleMessage (node:internal/modules/esm/worker:199:24)
    at checkForMessages (node:internal/modules/esm/worker:141:28)
    at process.<anonymous> (node:internal/modules/esm/worker:160:5)
┌──────────────────────────────────────────────────────────┐
│ Error isn't helpful? See https://vike.dev/errors#verbose │
└──────────────────────────────────────────────────────────┘
20:35:22 [vike][request(1)] HTTP response / 500
```

## Notes
- Yarn with PnP (Plug'n'Play) is used
- Similar #123

**Comment by rtritto** [comment]
Retry with `vike` v0.4.196 and `vite` v5.4.6
- PnP:

  ```console
    VITE v5.4.6  ready in 1980 ms
  
    ➜  Local:   http://localhost:3000/
    ➜  Network: use --host to expose
    ➜  press h + enter to show help
  15:55:43 [vike][request(1)] HTTP request: /
  
  🌼   daisyUI 4.12.10
  ├─ ✔︎ 1 theme added             https://daisyui.com/docs/themes
  ╰─ ❤︎ Support daisyUI project:  https://opencollective.com/daisyui
  
  15:55:43 [vite] Error when evaluating SSR module /src/pages/index/Movies.tsx: failed to import "vike-solid-query"
  |- Error: Qualified path resolution failed: we looked for the following paths, but none could be accessed.
  
  Source path: C:\template-vike-solid-daisyui\.yarn\__virtual__\vike-solid-query-virtual-5e8ba09589\3\Users\Computer\AppData\Local\Yarn\Berry\cache\vike-solid-query-npm-0.0.1-37c4e8e89f-10c0.zip\node_modules\vike-solid-query\dist\src\QueryBoundary
  Not found: C:\template-vike-solid-daisyui\.yarn\__virtual__\vike-solid-query-virtual-5e8ba09589\3\Users\Computer\AppData\Local\Yarn\Berry\cache\vike-solid-query-npm-0.0.1-37c4e8e89f-10c0.zip\node_modules\vike-solid-query\dist\src\QueryBoundary
  
      at makeError (C:\template-vike-solid-daisyui\.pnp.cjs:12259:34)
      at resolveUnqualified (C:\template-vike-solid-daisyui\.pnp.cjs:13991:13)
      at resolveRequest (C:\template-vike-solid-daisyui\.pnp.cjs:14031:14)
      at Object.resolveRequest (C:\template-vike-solid-daisyui\.pnp.cjs:14087:26)
      at resolve$1 (file:///C:/template-vike-solid-daisyui/.pnp.loader.mjs:2043:21)
      at nextResolve (node:internal/modules/esm/hooks:750:28)
      at Hooks.resolve (node:internal/modules/esm/hooks:238:30)
      at MessagePort.handleMessage (node:internal/modules/esm/worker:199:24)
      at [nodejs.internal.kHybridDispatch] (node:internal/event_target:816:20)
      at MessagePort.<anonymous> (node:internal/per_context/messageport:23:28)
  
  15:55:43 [vite] Error when evaluating SSR module /src/pages/index/+Page.tsx: failed to import "vike-solid-query"
  |- Error: Qualified path resolution failed: we looked for the following paths, but none could be accessed.
  
  Source path: C:\template-vike-solid-daisyui\.yarn\__virtual__\vike-solid-query-virtual-5e8ba09589\3\Users\Computer\AppData\Local\Yarn\Berry\cache\vike-solid-query-npm-0.0.1-37c4e8e89f-10c0.zip\node_modules\vike-solid-query\dist\src\QueryBoundary
  Not found: C:\template-vike-solid-daisyui\.yarn\__virtual__\vike-solid-query-virtual-5e8ba09589\3\Users\Computer\AppData\Local\Yarn\Berry\cache\vike-solid-query-npm-0.0.1-37c4e8e89f-10c0.zip\node_modules\vike-solid-query\dist\src\QueryBoundary
  
      at makeError (C:\template-vike-solid-daisyui\.pnp.cjs:12259:34)
      at resolveUnqualified (C:\template-vike-solid-daisyui\.pnp.cjs:13991:13)
      at resolveRequest (C:\template-vike-solid-daisyui\.pnp.cjs:14031:14)
      at Object.resolveRequest (C:\template-vike-solid-daisyui\.pnp.cjs:14087:26)
      at resolve$1 (file:///C:/template-vike-solid-daisyui/.pnp.loader.mjs:2043:21)
      at nextResolve (node:internal/modules/esm/hooks:750:28)
      at Hooks.resolve (node:internal/modules/esm/hooks:238:30)
      at MessagePort.handleMessage (node:internal/modules/esm/worker:199:24)
      at [nodejs.internal.kHybridDispatch] (node:internal/event_target:816:20)
      at MessagePort.<anonymous> (node:internal/per_context/messageport:23:28)
  
  15:55:43 [vite] Error when evaluating SSR module virtual:vike:pageConfigValuesAll:server:/src/pages/index: failed to import "vike-solid-query"     
  |- Error: Qualified path resolution failed: we looked for the following paths, but none could be accessed.
  
  Source path: C:\template-vike-solid-daisyui\.yarn\__virtual__\vike-solid-query-virtual-5e8ba09589\3\Users\Computer\AppData\Local\Yarn\Berry\cache\vike-solid-query-npm-0.0.1-37c4e8e89f-10c0.zip\node_modules\vike-solid-query\dist\src\QueryBoundary
  Not found: C:\template-vike-solid-daisyui\.yarn\__virtual__\vike-solid-query-virtual-5e8ba09589\3\Users\Computer\AppData\Local\Yarn\Berry\cache\vike-solid-query-npm-0.0.1-37c4e8e89f-10c0.zip\node_modules\vike-solid-query\dist\src\QueryBoundary
  
      at makeError (C:\template-vike-solid-daisyui\.pnp.cjs:12259:34)
      at resolveUnqualified (C:\template-vike-solid-daisyui\.pnp.cjs:13991:13)
      at resolveRequest (C:\template-vike-solid-daisyui\.pnp.cjs:14031:14)
      at Object.resolveRequest (C:\template-vike-solid-daisyui\.pnp.cjs:14087:26)
      at resolve$1 (file:///C:/template-vike-solid-daisyui/.pnp.loader.mjs:2043:21)
      at nextResolve (node:internal/modules/esm/hooks:750:28)
      at Hooks.resolve (node:internal/modules/esm/hooks:238:30)
      at MessagePort.handleMessage (node:internal/modules/esm/worker:199:24)
      at [nodejs.internal.kHybridDispatch] (node:internal/event_target:816:20)
      at MessagePort.<anonymous> (node:internal/per_context/messageport:23:28)
  
  15:55:43 [vike][request(1)][Error] An error was thrown:
  Error: Qualified path resolution failed: we looked for the following paths, but none could be accessed.
  
  Source path: C:\template-vike-solid-daisyui\.yarn\__virtual__\vike-solid-query-virtual-5e8ba09589\3\Users\Computer\AppData\Local\Yarn\Berry\cache\vike-solid-query-npm-0.0.1-37c4e8e89f-10c0.zip\node_modules\vike-solid-query\dist\src\QueryBoundary
  Not found: C:\template-vike-solid-daisyui\.yarn\__virtual__\vike-solid-query-virtual-5e8ba09589\3\Users\Computer\AppData\Local\Yarn\Berry\cache\vike-solid-query-npm-0.0.1-37c4e8e89f-10c0.zip\node_modules\vike-solid-query\dist\src\QueryBoundary
  
      at makeError (C:\template-vike-solid-daisyui\.pnp.cjs:12259:34)
      at resolveUnqualified (C:\template-vike-solid-daisyui\.pnp.cjs:13991:13)
      at resolveRequest (C:\template-vike-solid-daisyui\.pnp.cjs:14031:14)
      at Object.resolveRequest (C:\template-vike-solid-daisyui\.pnp.cjs:14087:26)
      at resolve$1 (file:///C:/template-vike-solid-daisyui/.pnp.loader.mjs:2043:21)
      at nextResolve (node:internal/modules/esm/hooks:750:28)
      at Hooks.resolve (node:internal/modules/esm/hooks:238:30)
      at MessagePort.handleMessage (node:internal/modules/esm/worker:199:24)
      at [nodejs.internal.kHybridDispatch] (node:internal/event_target:816:20)
      at MessagePort.<anonymous> (node:internal/per_context/messageport:23:28)
  15:55:43 [vike][request(1)] HTTP response / 500
  ```
- node-modules:

  ```console
  VITE v5.4.6  ready in 852 ms
  
    ➜  Local:   http://localhost:3000/
    ➜  Network: use --host to expose
    ➜  press h + enter to show help
  16:00:09 [vike][request(1)] HTTP request: /
  
  🌼   daisyUI 4.12.10
  ├─ ✔︎ 1 theme added             https://daisyui.com/docs/themes
  ╰─ ❤︎ Support daisyUI project:  https://opencollective.com/daisyui
  
  16:00:09 [vite] Error when evaluating SSR module /src/pages/index/Movies.tsx: failed to import "vike-solid-query"
  |- Error: Cannot find module 'C:\template-vike-solid-daisyui\node_modules\vike-solid-query\dist\src\QueryBoundary' imported from C:\template-vike-solid-daisyui\node_modules\vike-solid-query\dist\src\index.js
      at finalizeResolution (node:internal/modules/esm/resolve:260:11)
      at moduleResolve (node:internal/modules/esm/resolve:920:10)
      at defaultResolve (node:internal/modules/esm/resolve:1119:11)
      at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:541:12)
      at ModuleLoader.resolve (node:internal/modules/esm/loader:510:25)
      at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:240:38)
      at ModuleJob._link (node:internal/modules/esm/module_job:126:49)
  
  16:00:09 [vite] Error when evaluating SSR module /src/pages/index/+Page.tsx: failed to import "vike-solid-query"
  |- Error: Cannot find module 'C:\template-vike-solid-daisyui\node_modules\vike-solid-query\dist\src\QueryBoundary' imported from C:\template-vike-solid-daisyui\node_modules\vike-solid-query\dist\src\index.js
      at finalizeResolution (node:internal/modules/esm/resolve:260:11)
      at moduleResolve (node:internal/modules/esm/resolve:920:10)
      at defaultResolve (node:internal/modules/esm/resolve:1119:11)
      at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:541:12)
      at ModuleLoader.resolve (node:internal/modules/esm/loader:510:25)
      at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:240:38)
      at ModuleJob._link (node:internal/modules/esm/module_job:126:49)
  
  16:00:09 [vite] Error when evaluating SSR module virtual:vike:pageConfigValuesAll:server:/src/pages/index: failed to import "vike-solid-query"
  |- Error: Cannot find module 'C:\template-vike-solid-daisyui\node_modules\vike-solid-query\dist\src\QueryBoundary' imported from C:\template-vike-solid-daisyui\node_modules\vike-solid-query\dist\src\index.js
      at finalizeResolution (node:internal/modules/esm/resolve:260:11)
      at moduleResolve (node:internal/modules/esm/resolve:920:10)
      at defaultResolve (node:internal/modules/esm/resolve:1119:11)
      at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:541:12)
      at ModuleLoader.resolve (node:internal/modules/esm/loader:510:25)
      at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:240:38)
      at ModuleJob._link (node:internal/modules/esm/module_job:126:49)
  
  16:00:09 [vike][request(1)][Error] An error was thrown:
  Error: Cannot find module 'C:\template-vike-solid-daisyui\node_modules\vike-solid-query\dist\src\QueryBoundary' imported from C:\template-vike-solid-daisyui\node_modules\vike-solid-query\dist\src\index.js
      at finalizeResolution (node:internal/modules/esm/resolve:260:11)
      at moduleResolve (node:internal/modules/esm/resolve:920:10)
      at defaultResolve (node:internal/modules/esm/resolve:1119:11)
      at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:541:12)
      at ModuleLoader.resolve (node:internal/modules/esm/loader:510:25)
      at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:240:38)
      at ModuleJob._link (node:internal/modules/esm/module_job:126:49) {
    code: 'ERR_MODULE_NOT_FOUND',
    url: 'file:///C:/template-vike-solid-daisyui/node_modules/vike-solid-query/dist/src/QueryBoundary'
  }
  ┌─────────────────────────────────────────────────────────────────────────────┐
  │ The error could be a CJS/ESM issue, see https://vike.dev/broken-npm-package │
  └─────────────────────────────────────────────────────────────────────────────┘
  16:00:09 [vike][request(1)] HTTP response / 500
  ```

**Comment by rtritto** [comment]
@phonzammi probably this issue can be fixed with #123, please can you do a check?

**Comment by brillout** [comment]
@phonzammi Let me know if you want me to have a look at it. It seems to be more of a JavaScript issue than a Solid (Query) one.

**Comment by phonzammi** [comment]
@rtritto, Sure, I'm currently working on it, but I haven’t finished yet because I had to prioritize another task.

**Comment by brillout** [comment]
@rtritto Some wip and pre-release at https://github.com/vikejs/vike-solid/pull/127.
